# -*- coding: utf-8 -*-
"""House Prices - Advanced Regression Techniques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsleiLyzrrQUGJ6bPEpgl3K7s0tOj4KR
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

# 1. Load dataset - CORRECTED FILE NAME
df = pd.read_csv('train (1).csv')

# 2. Select relevant features
features_to_select = [
    'TotRmsAbvGrd',        # total rooms
    'LotArea',             # lot area
    'Neighborhood',        # location (categorical)
    'GrLivArea',           # ground living area (size)
    'OverallQual',         # overall quality
    'YearBuilt'            # year built
]
target = 'SalePrice'

# 3. Data Cleaning and Preprocessing
df = df.dropna(subset=features_to_select + [target])

# **CORRECTION: Use One-Hot Encoding for 'Neighborhood' (location)**
df_encoded = pd.get_dummies(df, columns=['Neighborhood'], drop_first=True)

# Define the numerical features and the final features list after encoding
num_features = ['TotRmsAbvGrd', 'LotArea', 'GrLivArea', 'OverallQual', 'YearBuilt']
encoded_features = [col for col in df_encoded.columns if col.startswith('Neighborhood_')]
all_features = num_features + encoded_features

# Optional: Standardize numerical features
scaler = StandardScaler()
df_encoded[num_features] = scaler.fit_transform(df_encoded[num_features])

# 4. Prepare data for modeling
X = df_encoded[all_features]
y = df_encoded[target]

# 5. Split data (80-20 train/test split)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# 6. Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# 7. Predict and Evaluate
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print('Model performance:')
print(f'Root Mean Squared Error (RMSE): {rmse:.2f}')
print(f'R2 Score: {r2:.3f}')

# 8. Test with a new input (example)
# Use iloc[[0]] to keep the structure needed for prediction
sample_input = X_test.iloc[[0]]
predicted_price = model.predict(sample_input)
print(f'Predicted price for sample input: {predicted_price[0]:.2f}')