# -*- coding: utf-8 -*-
"""Matrix_Operations_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V97qh2jlHztrkRphQ2ZuDC-uI1V_hNSI
"""

# 1. IMPORTS AND UTILITY FUNCTIONS
import numpy as np

def input_matrix(name="Matrix"):
    """
    1.1. Prompts the user to input the dimensions and elements of a matrix.
    Includes robust error handling for input dimensions and element count.
    """
    # 1.1.1. Get valid dimensions (rows and columns)
    while True:
        try:
            rows = int(input(f"Enter number of rows for {name}: "))
            cols = int(input(f"Enter number of columns for {name}: "))
            if rows <= 0 or cols <= 0:
                print("Dimensions must be positive integers. Try again.")
                continue
            break
        except ValueError:
            print("Invalid input for dimensions. Please enter integers.")

    print(f"Enter the elements of {name} row-wise (space separated):")
    matrix = []

    # 1.1.2. Get elements row by row with validation
    for i in range(rows):
        while True:
            try:
                row_input = input(f"Row {i+1}: ").split()
                row = list(map(float, row_input))

                if len(row) != cols:
                    print(f"Error: Expected {cols} elements, but got {len(row)}. Please enter row {i+1} again.")
                    continue

                matrix.append(row)
                break
            except ValueError:
                print("Invalid element input. Please enter numbers separated by spaces.")

    return np.array(matrix)

def display_matrix(mat, name="Result"):
    """
    1.2. Displays a NumPy matrix in a structured format, including its dimensions.
    """
    print(f"\n--- {name} ({mat.shape[0]}x{mat.shape[1]}) ---")
    print(mat)

# 2. MAIN APPLICATION FUNCTION
def main():
    """
    2.1. Main function for the interactive tool interface and operation logic.
    """
    print("\n=== Matrix Operations Tool ===")
    print("Available operations:")
    print("1. Addition (A + B)")
    print("2. Subtraction (A - B)")
    print("3. Multiplication (A x B)")
    print("4. Transpose (A^T)")
    print("5. Determinant Calculation (det(A))")
    print("0. Exit")

    # 2.2. Operation Loop
    while True:
        choice = input("\nSelect an operation (0-5): ")

        # 2.3. Operation Logic (Requires two matrices)
        if choice == '1':  # Addition
            print("\nMatrix Addition Selected.")
            mat1 = input_matrix("Matrix A")
            mat2 = input_matrix("Matrix B")
            if mat1.shape == mat2.shape:
                result = mat1 + mat2
                display_matrix(result, "A + B")
            else:
                print("Error: Matrices must be of same dimensions for addition.")

        elif choice == '2':  # Subtraction
            print("\nMatrix Subtraction Selected.")
            mat1 = input_matrix("Matrix A")
            mat2 = input_matrix("Matrix B")
            if mat1.shape == mat2.shape:
                result = mat1 - mat2
                display_matrix(result, "A - B")
            else:
                print("Error: Matrices must be of same dimensions for subtraction.")

        elif choice == '3':  # Multiplication
            print("\nMatrix Multiplication Selected.")
            mat1 = input_matrix("Matrix A")
            mat2 = input_matrix("Matrix B")
            if mat1.shape[1] == mat2.shape[0]:
                result = np.dot(mat1, mat2)
                display_matrix(result, "A x B")
            else:
                print("Error: Columns of A must equal rows of B for multiplication.")

        # 2.4. Operation Logic (Requires one matrix)
        elif choice == '4':  # Transpose
            print("\nMatrix Transpose Selected.")
            mat = input_matrix("Matrix")
            display_matrix(mat.T, "Transpose")

        elif choice == '5':  # Determinant
            print("\nDeterminant Calculation Selected.")
            mat = input_matrix("Square Matrix")
            if mat.shape[0] == mat.shape[1]:
                det = np.linalg.det(mat)
                print(f"\nDeterminant: {det:.4f}")
            else:
                print("Error: Matrix must be square to calculate determinant.")

        # 2.5. Exit and Error Handling
        elif choice == '0':
            print("Exiting Matrix Operations Tool. Goodbye!")
            break
        else:
            print("Invalid choice. Try again.")

# 3. EXECUTION POINT
if __name__ == "__main__":
    main()2