# -*- coding: utf-8 -*-
"""Speech_to_Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAH4MObLKIP-job0XDoLGtXKGQhEeAxt
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the CSV file
df = pd.read_csv('train (1).csv')

# Basic info
print("Data Shape:", df.shape)
print("Column Sample:", df.columns[:8])

# Selecting relevant columns for demo
selected_column = 'SalePrice'
numeric_columns = ['SalePrice', 'GrLivArea', 'LotArea', 'OverallQual']

# Calculating the average of a selected column
avg_price = df[selected_column].mean()
print(f"Average {selected_column}: {avg_price:,.2f}")

# Bar Chart (OverallQual vs Average SalePrice)
qual_price = df.groupby('OverallQual')['SalePrice'].mean().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
qual_price.plot(kind='bar', color='skyblue')
plt.title('Average Sale Price by Overall Quality')
plt.xlabel('Overall Quality')
plt.ylabel('Average Sale Price ($)')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('bar_chart.png') # Replaced plt.show()
plt.close()

# Scatter Plot (GrLivArea vs SalePrice)
plt.figure(figsize=(10, 6))
plt.scatter(df['GrLivArea'], df['SalePrice'], alpha=0.5, color='darkgreen')
plt.title('Sale Price vs Ground Living Area')
plt.xlabel('Ground Living Area (sq ft)')
plt.ylabel('Sale Price ($)')
plt.tight_layout()
plt.savefig('scatter_plot.png') # Replaced plt.show()
plt.close()

# Heatmap (correlation between selected numeric features)
corr = df[numeric_columns].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Feature Correlation Heatmap')
plt.tight_layout()
plt.savefig('heatmap.png') # Replaced plt.show()
plt.close()

# Insights and Observations
print("\nInsights & Observations:")
print("- Houses with higher overall quality tend to have higher average sale prices.")
print("- There is a strong positive correlation (0.82) between OverallQual and SalePrice.")
print("- There is a strong positive correlation (0.71) between ground living area (GrLivArea) and sale price.")
print("- LotArea has a weak correlation (0.26) with SalePrice compared to GrLivArea and OverallQual.")